### ISSUE TITLE
400 Bad Request Error from fortune cog

### ISSUE THREAD

**Issue by aptgetmoo** [aptgetmoo/moobot#11]
not really sure what causes this...
traceback:

```python
Ignoring exception in command fortune
Traceback (most recent call last):
File "/home/joe/moobot/.venv/lib/python3.5/site-packages/discord/ext/commands/
core.py", line 50, in wrapped
ret = yield from coro(*args, **kwargs)
File "/home/joe/moobot/cogs/plugins/fortune.py", line 68, in fortune
await self.bot.say(cowsay)
File "/home/joe/moobot/.venv/lib/python3.5/site-packages/discord/ext/commands/bot.py", line 309, in _augmented_msg
msg = yield from coro
File "/home/joe/moobot/.venv/lib/python3.5/site-packages/discord/client.py", line 1152, in send_message
data = yield from self.http.send_message(channel_id, content, guild_id=guild_id, tts=tts, embed=embed)
File "/home/joe/moobot/.venv/lib/python3.5/site-packages/discord/http.py", line 211, in request
raise HTTPException(r, data)
discord.errors.HTTPException: BAD REQUEST (status code: 400)


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/joe/moobot/.venv/lib/python3.5/site-packages/discord/ext/commands/bot.py", line 848, in process_commands
    yield from command.invoke(ctx)
  File "/home/joe/moobot/.venv/lib/python3.5/site-packages/discord/ext/commands/core.py", line 369, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "/home/joe/moobot/.venv/lib/python3.5/site-packages/discord/ext/commands/core.py", line 54, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: HTTPException: BAD REQUEST (status code: 400)
INFO:discord.gateway:Unhandled event CHANNEL_PINS_UPDATE
Ignoring exception in command fortune
Traceback (most recent call last):
  File "/home/joe/moobot/.venv/lib/python3.5/site-packages/discord/ext/commands/core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/home/joe/moobot/cogs/plugins/fortune.py", line 68, in fortune
    await self.bot.say(cowsay)
  File "/home/joe/moobot/.venv/lib/python3.5/site-packages/discord/ext/commands/
bot.py", line 309, in _augmented_msg
    msg = yield from coro
  File "/home/joe/moobot/.venv/lib/python3.5/site-packages/discord/client.py", line 1152, in send_message
    data = yield from self.http.send_message(channel_id, content, guild_id=guild_id, tts=tts, embed=embed)
  File "/home/joe/moobot/.venv/lib/python3.5/site-packages/discord/http.py", line 211, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: BAD REQUEST (status code: 400)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/joe/moobot/.venv/lib/python3.5/site-packages/discord/ext/commands/bot.py", line 848, in process_commands
    yield from command.invoke(ctx)
  File "/home/joe/moobot/.venv/lib/python3.5/site-packages/discord/ext/commands/core.py", line 369, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "/home/joe/moobot/.venv/lib/python3.5/site-packages/discord/ext/commands/core.py", line 54, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: HTTPException: BAD REQUEST (status code: 400)

```

**Comment by SuperWool** [comment]
who knows lmao

**Comment by aptgetmoo** [comment]
@SuperWool would you happen to know if it's from a specific user/to a specific channel?
